spring.application.name=codingshuttleRESTAPI

spring.datasource.url=postgresql://neondb_owner:npg_KuAPCIb1rgc3@ep-mute-hat-aqizpt59-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KuAPCIb1rgc3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}